### ISSUE TITLE
Having trouble building shim on Solaris system

### ISSUE THREAD

**Issue by mattroisang** [rhinstaller/shim#36]
Hi, 

When I try to build shim 0.7 on a Solaris system, I get the following error:
gcc -nostdlib -znocombreloc -shared -fPIC -Bsymbolic -L/root/secured2/gnu-efi-3.0u/gnuefi -L/root/secured2/root/X86_64/lib/ -LCryptlib -LCryptlib/OpenSSL /root/secured2/gnu-efi-3.0u/gnuefi/crt0-efi-x86_64.o  shim.o   -o shim
Text relocation remains                         referenced
    against symbol                  offset      in file
ImageBase                           0x9         /root/secured2/gnu-efi-3.0u/gnuefi/crt0-efi-x86_64.o
_relocate                           0x19        /root/secured2/gnu-efi-3.0u/gnuefi/crt0-efi-x86_64.o
efi_main                            0x20        /root/secured2/gnu-efi-3.0u/gnuefi/crt0-efi-x86_64.o
_DYNAMIC                            0x10        /root/secured2/gnu-efi-3.0u/gnuefi/crt0-efi-x86_64.o
ld: fatal: relocations remain against allocatable but non-writable sections
collect2: error: ld returned 1 exit status
gmake: *** [shim] Error 1

This object file "crt0-efi-x86_64.o" is built with -fPIC, so I am not sure why the errors arise.  Has anyone build shim 0.7 on Solaris and seen this issue?  Any help is much appreciated.

Thanks,
Matt

**Comment by mattroisang** [comment]
It appears changing the linker to GNU Linker (gld) help.

**Comment by vathpela** [comment]
With that in mind, can we close this out? I'm not going to be able to guess what every system out there has named the GNU linker, but LD is a variable so setting it is simple?

**Comment by mattroisang** [comment]
Yes you can close this out
