### ISSUE TITLE
shim 0.8 can't be executed in vmware 10.0.1.41495

### ISSUE THREAD

**Issue by Jobcrazy** [rhinstaller/shim#39]
I've complile and test shim 0.2/0.3/0.7,and shim works fine.

but I complile shim 0.8 then test it in vmware, the vmware halt.

My gcc version:

# /usr/local/gcc/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/gcc/bin/gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc/libexec/gcc/x86_64-linux-gnu/4.7.4/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ./configure --enable-languages=c,c++ --prefix=/usr/local/gcc --enable-shared --enable-linker-build-id --without-included-gettext --enable-threads=posix --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-plugin --with-system-zlib --disable-browser-plugin --with-arch-directory=amd64 --enable-multiarch --disable-werror --with-arch-32=i686 --disable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.4 (GCC)

**Comment by Jobcrazy** [comment]
I‘ve just tried gcc 4.9.2, and shim(0.8/mater) still halt

**Comment by lcp** [comment]
Does this work for you?
https://github.com/lcp/shim/commit/61f1bfea2250c38b6c381a3876b41acf007f4289

There is a known issue that objcopy in binutils < 2.24 didn't support asterisks and some sections of the efi file would be gone. The change(*) was introduced between 0.7 and 0.8.

(*) https://github.com/rhinstaller/shim/commit/99d7b5e858945b8bb160fe3fea77596b2daf07ff

**Comment by Jobcrazy** [comment]
Thanks, I update binutils and it works.
