### ISSUE TITLE
shim 0.7: pesign: could not parse signature list in EFI binary

### ISSUE THREAD

**Issue by mattroisang** [rhinstaller/shim#40]
When building shim 0.7 on a Solaris system, I get the error "pesign: could not parse signature list in EFI binary", you can see longer output below.  I am able to sign other efi binary with pesign, so the issue is not in pesign or my certificate, but it has to do with how my binary is built I guess.  Has anyone seen this issue?

Output:
...
...
certutil -A -n 'my CA' -d certdb/ -t CT,CT,CT -i ca.crt
pk12util -d certdb/ -i shim.p12 -W "" -K ""
pk12util: PKCS12 IMPORT SUCCESSFUL
certutil -d certdb/ -A -i shim.crt -n shim -t u
Notice: Trust flag u is set automatically if the private key is present.
objcopy -j .text -j .sdata -j .data \
        -j .dynamic -j .dynsym  -j .rel \
        -j .rela -j .reloc -j .eh_frame \
        -j .vendor_cert \
        --target=elf64-x86-64-sol2 MokManager.so MokManager.efi
objcopy -j .text -j .sdata -j .data \
        -j .dynamic -j .dynsym  -j .rel \
        -j .rela -j .reloc -j .eh_frame \
        -j .debug_info -j .debug_abbrev -j .debug_aranges \
        -j .debug_line -j .debug_str -j .debug_ranges \
        --target=elf64-x86-64-sol2 MokManager.so MokManager.efi.debug
pesign -n certdb -i MokManager.efi -c "shim" -s -o MokManager.efi.signed -f
pesign: could not parse signature list in EFI binary

**Comment by vathpela** [comment]
So that probably means the data directory is malformed, but it's hard to say - somebody's going to have to do a build that works with the same code tree on a linux machine and compare the two binaries by hand to see what's different.

**Comment by vathpela** [comment]
Though that being said, pesign certainly isn't well tested on solaris - it's possible we've got a struct packing error someplace, for example.  What version of pesign is this with?

**Comment by mattroisang** [comment]
Hi vathpela,

It was pesign-0.109, but I figured it out, the problem was with my build environment.
