### ISSUE TITLE
shim needs to be resigned to permit GRUB2 to chainload Windows bootloader with Secure Boot enabled

### ISSUE THREAD

**Issue by cmurf** [rhinstaller/shim#42]
This bug:
SecureBoot enabled causes Win 8 UEFI to not start from grub
https://bugzilla.redhat.com/show_bug.cgi?id=1170245

can be fixed with this patch:
https://build.opensuse.org/package/view_file/openSUSE:Factory/grub2/grub2-secureboot-chainloader.patch?expand=1

But shim needs to be resigned in order to make all of this possible somehow.

**Comment by mjg59** [comment]
This should be entirely unnecessary - LoadImage() and StartImage() should work fine in this case.

**Comment by cmurf** [comment]
Well that's what I thought, but Peter says otherwise and asked for this bug to get filed, so that's what I did.
https://meetbot.fedoraproject.org/fedora-meeting/2015-09-02/workstation.2015-09-02-14.01.log.html
14:22:06 <pjones> yeah, we need to get the patch upstream for this, and it wasn't on my TODO for shim last release - can somebody file an issue here: https://github.com/rhinstaller/shim/issues ?

**Comment by mjg59** [comment]
The patch is desirable for other reasons, but it's avoiding this bug rather than fixing it.
