### ISSUE TITLE
Cannot build shim 0.9 on Solaris system

### ISSUE THREAD

**Issue by mattroisang** [rhinstaller/shim#54]
Hi,

shim 0.9 does not build on Solaris systems.  I have attached some patches if anyone is interested.  Sorry if this is not the right place to post.

Thanks,
Mat Troi
[patches.tar.gz](https://github.com/rhinstaller/shim/files/394645/patches.tar.gz)

**Comment by vathpela** [comment]
We are interested, but if you could please post these patches as individual pull requests with real changelog entries on each, that would be a significantly more normal process to aid in properly merging fixes.

**Comment by mattroisang** [comment]
Hi vathpela,  I have created the pull request with a changelog.  Please let me know if I do it correctly/incorrectly.  Thanks.
