### ISSUE TITLE
"Failed to set variable: (2) Invalid Parameter" when enrolling MOK

### ISSUE THREAD

**Issue by adempewolff** [rhinstaller/shim#55]
I'm unsure if this is a bug in shim, mokutil, or user error.  I also filed a bug against mokutil here: https://bugs.launchpad.net/ubuntu/+source/mokutil/+bug/1600452

Feel free to close the issue if you can determine that it's not related to Shim (although any hints on what might be causing it would be appreciated!)

## Testing Environment:
Lenovo Thinkpad P50, fresh install of Ubuntu 16.04 64bit

```
$ apt-cache policy mokutil
mokutil:
  Installed: 0.3.0-0ubuntu3
  Candidate: 0.3.0-0ubuntu3
  Version table:
 *** 0.3.0-0ubuntu3 500
        500 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy shim
shim:
  Installed: 0.8-0ubuntu2
  Candidate: 0.8-0ubuntu2
  Version table:
 *** 0.8-0ubuntu2 500
        500 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

## Steps to reproduce:
(1) do not disable SecureBoot as suggested during the install.

(2) install virtualbox-5.0 from the virtualbox ppa (deb http://download.virtualbox.org/virtualbox/debian xenial contrib)

(3) Follow instructions here to manually sign the vboxdrv kernel module (https://askubuntu.com/questions/760671/could-not-load-vboxdrv-after-upgrade-to-ubuntu-16-04-and-i-want-to-keep-secur/768310#768310)

```
$ openssl req -new -x509 -newkey rsa:2048 -keyout MOK.priv -outform DER -out MOK.der -nodes -days 36500 -subj "/CN=Descriptive name/"
$ sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./MOK.priv ./MOK.der $(modinfo -n vboxdrv)
$ sudo mokutil --import MOK.der
```

(enter password)

(4) reboot, click "enroll mok", "continue", "yes", enter password, (screenshots here: https://sourceware.org/systemtap/wiki/SecureBoot)

## Expected behavior:

new mok will be enrolled and I will be asked to reboot (several users from the original askubuntu answer indicated that these exact steps worked for them.

## Actual behaviour:

"Error: Failed to set variable: (2) Invalid Parameter"

## Troubleshooting steps taken:
- tried different passwords, and was able to eliminate that being the cause.
- found relevant lines of code producing the error: lines 919-931 in https://github.com/rhinstaller/shim/blob/master/MokManager.c

```
  efi_status = uefi_call_wrapper(RT->SetVariable, 5, db_name,
            &shim_lock_guid,
            EFI_VARIABLE_NON_VOLATILE
            | EFI_VARIABLE_BOOTSERVICE_ACCESS
            | EFI_VARIABLE_APPEND_WRITE,
            MokNewSize, MokNew);
 }

 if (efi_status != EFI_SUCCESS) {
  console_error(L"Failed to set variable", efi_status);
  return efi_status;
}
```

- unable to find where uefi_call_wrapper() is defined

ProblemType: Bug
DistroRelease: Ubuntu 16.04
Package: mokutil 0.3.0-0ubuntu3
ProcVersionSignature: Ubuntu 4.4.0-28.47-generic 4.4.13
Uname: Linux 4.4.0-28-generic x86_64
ApportVersion: 2.20.1-0ubuntu2.1
Architecture: amd64
CurrentDesktop: Unity
Date: Sat Jul 9 18:56:59 2016
InstallationDate: Installed on 2016-07-08 (0 days ago)
InstallationMedia: Ubuntu 16.04 LTS "Xenial Xerus" - Release amd64 (20160420.1)
SourcePackage: mokutil
UpgradeStatus: No upgrade log present (probably fresh install)

**Comment by srazzaque** [comment]
This also just happened to me right now - Thinkpad X260. Not with VirtualBox, but tp_smapi-dkms. Same versions of mokutil and shim.

**Comment by lcp** [comment]
In the UEFI Plugfest Taipei this year, I found that Lenovo server firmware didn't support EFI_VARIABLE_APPEND_WRITE although it's already in the UEFI SPEC for years, and their server showed the same issue as you reported. From what I know, their firmware team is still working on that, so I won't be surprised if their laptop firmware had the same problem.

**Comment by adempewolff** [comment]
Thanks for the feedback/hypothesis.  Maybe I'll try filing a bug-report with Lenovo and see if I can get any information from them.  Is there any way to verify that this is the problem?

**Comment by lcp** [comment]
You can write a simple EFI app to write a variable with EFI_VARIABLE_APPEND_WRITE.
The example application in gnu-efi is a good start:
https://sourceforge.net/p/gnu-efi/code/ci/master/tree/apps/t2.c

Invoke RT->SetVariable with an arbitrary GUID, variable name and an one bytes variable, and then print the returned status with Print(L"Return %r", status). In the UEFI with the problem, you will get "Invalid Parameter" while the application will work fine in other UEFI application.

PS. Remember to remove the variable if it writes successfully.

**Comment by jpstacey** [comment]
I can confirm this behaviour on a Thinkpad X1 Carbon just now.

**Comment by dmgerman** [comment]
I also confirm the issue on the Thinpad X1 Carbon

**Comment by adempewolff** [comment]
Okay, I'll try to review the EFI documentation and create a test app as you suggest.  Once we have some more formal evidence that this is the problem we can all start filing bug reports with Lenovo.  Unfortunately, given my work schedule, I probably won't have time to dive into the EFI documentation for another couple weeks.  If any of the other Thinkpad users want to take a crack at it beforehand, please by all means go for it.

**Comment by marcelofernandez** [comment]
I can also confirm the issue on the Thinpad T460s.

**Comment by marcelofernandez** [comment]
Hi, @lcp, could you give me an example snippet of code of the call you're describing? 

I'll try to compile and execute it here in my test machine.

Regards

**Comment by lcp** [comment]
Here is the code:
https://github.com/lcp/uefi-fun/tree/master/WriteAppend
You will need at least make, gcc, and gnu-efi to compile the code. If crt0-efi-x86_64.o is not in /usr/lib64, you can specify the EFI_PATH to change the path. For example, type "make EFI_PATH=/usr/lib64/gnuefi" if crt0-efi-x86_64.o is in /usr/lib64/gnuefi.

**Comment by marcelofernandez** [comment]
Thank you @lcp , I'll try to execute it and get back with results.

**Comment by marcelofernandez** [comment]
Hello @lcp,

I've succesfully compiled and executed your example, and given the output I can confirm the Lenovo firmware **doesn't support** the EFI_VARIABLE_APPEND_WRITE flag.

I've used the gnu-efi library from Ubuntu 16.04 for compilation, and following the instructions here [1], I've installed the EFI shell executable from Tiano Core site [2]. Also, I had to disable Secure Boot (because the shell is not signed, I suppose); I think this does not affect the result of the program, right?

I've uploaded a couple of photos [3], one of the error itself, and another one of the BIOS & hardware version (the BIOS is 1.13, the latest one as of today [4]).

[1] http://www.rodsbooks.com/efi-programming/hello.html
[2] https://edk2.svn.sourceforge.net/svnroot/edk2/trunk/edk2/EdkShellBinPkg/FullShell/X64/Shell_Full.efi
[3] http://imgur.com/a/9eRHe
[4] http://support.lenovo.com/ar/es/products/Laptops-and-netbooks/ThinkPad-T-Series-laptops/ThinkPad-T460s?beta=false

Thank you

**Comment by lcp** [comment]
Yep, Secure Boot doesn't matter in this case. Thanks for your confirmation. I guess Lenovo won't support it in the short term. We probably have to patch MokManager to make it compatible with Lenovo machines...

**Comment by lcp** [comment]
Just sent a pull request to fix the issue.
https://github.com/rhinstaller/shim/pull/60

**Comment by lcp** [comment]
Since I don't have any Lenovo machine with UEFI, I will appreciate anyone who can help to verify the patch.
The steps:
1. disable Secure Boot
2. replace MokManager.efi in the system (remember to back up the file)
3. enroll an arbitrary key and check the key with "mokutil -l"

**Comment by marcelofernandez** [comment]
Hello @lcp, it worked!
It took me a while to figure out how to build shim (there are a couple of different paths in Ubuntu), but with the new MokManager I enrolled a new key without problems, and now I can load signed virtualbox modules with SB enabled.

Is there anything else I can do?

Regards

**Comment by marcelofernandez** [comment]
In other news, I wanted to test the new Lenovo's BIOS version, 1.14 [1], just to make sure the bug isn't already fixed:

[1] http://support.lenovo.com/ar/es/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t460s/downloads/DS112118

**Comment by adempewolff** [comment]
@marcelofernandez I'm guessing that BIOS update is just fixing the massive Thinkpad security vulnerability discovered at the beginning of the month (http://www.digitaltrends.com/computing/lenovo-security-vulnerability/).  I can probably figure it out myself (I suspect the main changes are just that the gnu-efi libraries are in /usr/lib) but would you mind sharing what paths you needed to change for Ubuntu if you happen to be online at the moment?

@lcp Wow, thank you! I'm really impressed with how responsive you were to this issue and how rapidly you came up with a fix.  If you ever find your way to Shanghai I owe you a drink and/or meal for sure!

**Comment by marcelofernandez** [comment]
@adempewolff, ok, that sounds correct, but I'll update anyway.

This is the output of "git diff" in a working-state shim directory in Ubuntu 16.04 as of today:

```diff
marcelo@marcelo-notebook:~/src/shim$ git diff
diff --git a/Makefile b/Makefile
index 640ecf2..158e7e6 100644
--- a/Makefile
+++ b/Makefile
@@ -9,15 +9,17 @@ LD            = $(CROSS_COMPILE)ld
 OBJCOPY                = $(CROSS_COMPILE)objcopy
 
 ARCH           = $(shell $(CC) -dumpmachine | cut -f1 -d- | sed s,i[3456789]86,ia32,)
-OBJCOPY_GTE224  = $(shell expr `$(OBJCOPY) --version |grep ^"GNU objcopy" | sed 's/^.version //g' | cut -f1-2 -d.` \>= 2.24)
+OBJCOPY_GTE224  = 1
+#OBJCOPY_GTE224  = /usr/bin/objcopy
 
 SUBDIRS                = Cryptlib lib
 
-LIB_PATH       = /usr/lib64
+LIB_PATH       = /usr/lib
 
 EFI_INCLUDE    := /usr/include/efi
 EFI_INCLUDES   = -nostdinc -ICryptlib -ICryptlib/Include -I$(EFI_INCLUDE) -I$(EFI_INCLUDE)/$(ARCH) -I$(EFI_INCLUDE)/protocol -I$(shell pwd)/include
-EFI_PATH       := /usr/lib64/gnuefi
+#EFI_PATH      := /usr/lib64/gnuefi
+EFI_PATH       := /usr/lib
 
 LIB_GCC                = $(shell $(CC) -print-libgcc-file-name)
 EFI_LIBS       = -lefi -lgnuefi --start-group Cryptlib/libcryptlib.a Cryptlib/OpenSSL/libopenssl.a --end-group $(LIB_GCC) 
diff --git a/shim.c b/shim.c
index ed01899..4845f3f 100644
--- a/shim.c
+++ b/shim.c
@@ -1118,7 +1118,7 @@ static EFI_STATUS handle_image (void *data, unsigned int datasize,
        EFI_STATUS efi_status;
        char *buffer;
        int i;
-       unsigned int size;
+       //unsigned int size;
        EFI_IMAGE_SECTION_HEADER *Section;
        char *base, *end;
        PE_COFF_LOADER_IMAGE_CONTEXT context;
```
The changes are:
1) Regex failing despite Ubuntu 16.04 has objcopy 2.26.1, but I didn't want to fix that.
2) Lib paths, as you suggested.
3) An unused variable giving a fatal error, so I commented that one.

Regards

**Comment by adempewolff** [comment]
Thanks, will test tonight provided the great firewall stops killing my connection to github and my clone can complete...

**Comment by adempewolff** [comment]
@lcp It worked for me too.  New key was enrolled successfully and I can see it with mokutils -l

**Comment by uklotzde** [comment]
Confirmed: Lenovo T460p with Fedora 24. Bug is still present in newest BIOS 2.08 published on 2016-07-21.

**Comment by lcp** [comment]
I forgot to mention that there are two pending patches needed to build against git HEAD:
https://github.com/rhinstaller/shim/pull/53
https://github.com/rhinstaller/shim/pull/56

But you guys made it anyway :-p

@adempewolff MokManager.efi.signed is equivalent to MokManager.efi except the signature from the auto-generated key.

Thank you all for the verification :-D

@vathpela Could you help to check in the patch?

**Comment by phocean** [comment]
Hello lcp,

I  just found this thread after having the issue with my new Thinkpad T460 on Fedora 24.
I successfully applied your patch, and it worked flawlessly.

I hope it will reach distributions soon.

Thank you very much !

**Comment by woftor** [comment]
Confirmed this bug on a X1 Carbon (20FB) with latest BIOS 1.17. Will try the fix later.

**Comment by arges** [comment]
Confirmed with Lenovo Yoga 260 and BIOS 1.47.

**Comment by vathpela** [comment]
So as I see it everything for this is merged?  I'm going to go ahead and close this issue now.  If I've misunderstood, please re-open with a brief summary of whatever I've missed.

**Comment by flying-squirrel** [comment]
I can confirm the error with my Thinkpad T460p. I tried to compile shim but I never came that far to get a file calle MokManager.efi. I only get a MokManager.o, then the compilation with 'make' stops with:
```
pesign -n certdb -i fbx64.efi -c "shim" -s -o fbx64.efi.signed -f
rm fbx64.efi mmx64.efi
```

I really don't get how I can get the needed file ... Searching for an answer for 2 hours didn't help.

Is there someone with an Lenovo Thinkpad who got the issue fixed and can provide his MokManager.efi?
