### ISSUE TITLE
shim + grub2 UEFI booting RHEL6.6/6.8?

### ISSUE THREAD

**Issue by CalvinHartwell** [rhinstaller/shim#65]
Hey,

My current customer is using some network devices which only support UEFI boot mode (no classic bios). I've managed to configure PXE to boot RHEL7.2 using shim and grub2 but I get an error "kernel version is too old" when attempting to boot RHEL6.6/6.8. 

Do you have any ideas about this issue? I'm going to try and compile shim/grub2 on RHEL6 and see if I can get it to work but I'm hitting a wall at the moment. 

Cheers,

- Calvin

**Comment by vathpela** [comment]
RHEL 6 doesn't have the patches needed to support Secure Boot at all, nor many of the changes in EFI infrastructure in the kernel needed to support them.  There's no reasonable way to support this, sorry.

**Comment by CalvinHartwell** [comment]
Thanks for the clarification @vathpela - I've written this work around for using legacy grub with satellite 6 to boot RHEL6 with UEFI: [https://github.com/RedHat-Consulting-UK/sat6-efi-converter](https://github.com/RedHat-Consulting-UK/sat6-efi-converter )
