### ISSUE TITLE
shim does not work correctly unless invoked via absolute path

### ISSUE THREAD

**Issue by mkdesu** [rhinstaller/shim#8]
When shim is invoked as e.g. _\EFI\BOOT\BOOTx64.EFI_, it correctly determines the location of _grubx64.efi_ and _MokManager.efi_. However, if it is invoked from the EFI Shell without the leading backslash, or from inside _EFI\BOOT_ directory as just _BOOTx64.EFI_, it is confused, tries to add forward slashes (which UEFI does not recognize), looks in upper-level directory instead, etc. A minor issue, but who knows — some UEFI firmware might decide to e.g. use pathes that don't start with a backslash.

**Comment by vathpela** [comment]
I believe this issue is resolved and can be closed.  If I'm wrong, please re-open it.
